#!/usr/bin/env python3
"""Generate backend/supabase/seed.sql from the app's bundled dataset (single source of truth).

Usage:  python3 data/export_seed.py
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / 'app/entry/src/main/ets/drugs/DrugDataset.ets'
OUT = ROOT / 'backend/supabase/seed.sql'
RISK = {'KR': 'KNOWN_RISK', 'PR': 'POSSIBLE_RISK', 'CR': 'CONDITIONAL_RISK', 'NL': 'NOT_LISTED'}


def q(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def main() -> None:
    text = SRC.read_text(encoding='utf-8')
    # d('ingredient', RISK, 'Class', [aliases...], ..., avoidCongenital)
    pattern = re.compile(r"d\('([^']+)',\s*(KR|PR|CR|NL),\s*'([^']*)',\s*\[([^\]]*)\].*?(true|false)\)", re.S)
    drugs, aliases = [], []
    for m in pattern.finditer(text):
        ingredient, risk, cls, alias_src, avoid = m.groups()
        drugs.append(f"({q(ingredient)}, {q(RISK[risk])}, {q(cls)}, {avoid})")
        for a in re.findall(r"'([^']+)'", alias_src):
            aliases.append(f"({q(a)}, {q(ingredient)})")
    lines = ['-- Generated by data/export_seed.py — do not edit by hand.',
             'insert into drugs (ingredient, risk, drug_class, avoid_congenital) values',
             ',\n'.join(drugs) + '\non conflict (ingredient) do update set risk = excluded.risk, '
             'drug_class = excluded.drug_class, avoid_congenital = excluded.avoid_congenital;',
             'insert into drug_aliases (alias, ingredient) values',
             ',\n'.join(aliases) + '\non conflict (alias) do update set ingredient = excluded.ingredient;']
    OUT.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'{len(drugs)} drugs, {len(aliases)} aliases -> {OUT.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
